import {
  Folder,
  FolderOpen,
  Star,
  Heart,
  Bookmark,
  Tag,
  Archive,
  Globe,
  Lock,
  Coffee,
  Briefcase,
  Home,
  User,
  Settings,
  Book,
  Music,
  Image,
  Video,
  Code,
  Gamepad2,
  ShoppingCart,
  Camera,
  Palette,
  Headphones,
  Smartphone,
  Car,
  Plane,
  Gift,
  MapPin,
  Calendar,
  Clock,
} from 'lucide-vue-next'

export const COLLECTION_ICONS = {
  folder: { component: Folder, label: 'Folder' },
  'folder-open': { component: FolderOpen, label: 'Open Folder' },
  star: { component: Star, label: 'Star' },
  heart: { component: Heart, label: 'Heart' },
  bookmark: { component: Bookmark, label: 'Bookmark' },
  tag: { component: Tag, label: 'Tag' },
  archive: { component: Archive, label: 'Archive' },
  globe: { component: Globe, label: 'Globe' },
  lock: { component: Lock, label: 'Lock' },
  coffee: { component: Coffee, label: 'Coffee' },
  briefcase: { component: Briefcase, label: 'Briefcase' },
  home: { component: Home, label: 'Home' },
  user: { component: User, label: 'User' },
  settings: { component: Settings, label: 'Settings' },
  book: { component: Book, label: 'Book' },
  music: { component: Music, label: 'Music' },
  image: { component: Image, label: 'Image' },
  video: { component: Video, label: 'Video' },
  code: { component: Code, label: 'Code' },
  gamepad: { component: Gamepad2, label: 'Games' },
  cart: { component: ShoppingCart, label: 'Shopping' },
  camera: { component: Camera, label: 'Camera' },
  palette: { component: Palette, label: 'Design' },
  headphones: { component: Headphones, label: 'Audio' },
  smartphone: { component: Smartphone, label: 'Mobile' },
  car: { component: Car, label: 'Travel' },
  plane: { component: Plane, label: 'Flight' },
  gift: { component: Gift, label: 'Gift' },
  map: { component: MapPin, label: 'Location' },
  calendar: { component: Calendar, label: 'Calendar' },
  clock: { component: Clock, label: 'Time' },
} as const

export type IconKey = keyof typeof COLLECTION_ICONS

export const COLLECTION_COLORS = [
  { name: 'Zinc', value: '#71717a' },
  { name: 'Blue', value: '#3b82f6' },
  { name: 'Green', value: '#10b981' },
  { name: 'Yellow', value: '#f59e0b' },
  { name: 'Red', value: '#ef4444' },
  { name: 'Purple', value: '#8b5cf6' },
  { name: 'Pink', value: '#ec4899' },
  { name: 'Orange', value: '#f97316' },
  { name: 'Teal', value: '#14b8a6' },
  { name: 'Indigo', value: '#6366f1' },
  { name: 'Emerald', value: '#059669' },
  { name: 'Rose', value: '#f43f5e' },
] as const
